POST http://localhost:3000/Account/token
Authorization: Bearer ZjAyWf2aJ38uLnhThZZGKxm43sPtyngmwPnPz3eRymkPq8yiZXGNuZxLTKXZheVx
Content-Type: application/json

{
    "line_login":{
        "access_token":"test"
    }
}

###
POST  https://8a5f-49-0-65-155.ngrok.io/Account/token
Authorization: Bearer ZjAyWf2aJ38uLnhThZZGKxm43sPtyngmwPnPz3eRymkPq8yiZXGNuZxLTKXZheVx
Content-Type: application/json

{
    "line_login":{
        "access_token":"test"
    }
}