POST {{baseurl}}/Account/token
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "line_login":{
        "access_token":"test"
    }
}

###
POST  https://3e49-49-0-65-155.ngrok.io/Account/token
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "line_login":{
        "id_token":"test"
    }
}