GET http://localhost:3000/Home/Song
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhYSIsImlhdCI6MTYzMzU3NDU0NSwiZXhwIjoxNjMzNTc0NTc1LCJpc3MiOiJhcGkuZGVtby50bGQifQ.7rVVnen8o9a3CAaYOFyEAIPXBOPEGAOk7QWFuQl85OwAsGb0RglGFUudPgsQS4gVh3p25ErYFicCW8B9HHhk-A

###
GET http://localhost:3000/Home/รัน
Authorization: Bearer ZZVdbXF4gUbY8mQjNGqoy7p2KY2FZffGFDAKpcZcdFbztedbntkv7rjbKQrooJrG

### error
GET http://localhost:3000/Home/acd$
Authorization: Bearer ZZVdbXF4gUbY8mQjNGqoy7p2KY2FZffGFDAKpcZcdFbztedbntkv7rjbKQrooJrG

### Error
GET http://localhost:3000/Home/error
Authorization: Bearer ZZVdbXF4gUbY8mQjNGqoy7p2KY2FZffGFDAKpcZcdFbztedbntkv7rjbKQrooJrG